### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by RoChess** [thyn/ua-parser-formfactor#2]
Noticed something weird that Windows 8.1 user-agent strings are not parsed.

Examples of those that seem to fail:
```
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
```
I can provide more details if needed.

**Comment by RoChess** [comment]
Found issue.

For Windows 8.1 with "Windows NT 6.3" userAgent, the ua-parser sets Major to an "8.1" float when it should be Major "8" integer and Minor "1" integer.

Code on our side does an int() conversion on Major and fails.

**Comment by thyn** [comment]
Created ticket

https://github.com/ua-parser/uap-core/issues/351

**Comment by RoChess** [comment]
Hi thyn,

Thank you for the ticket.

Issue also exists for "XP" which should be put in as 6.0, or "Vista" as 6.1, and help me if people still use it, but I wouldn't bother with Windows ME or 95/98/98SE :)

We modified our table to store as nvarchar(20) for now on OsMajor instead of an int(), as showing "Windows 6.0" will probably be confusing for people. They will instantly recognize "XP", so maybe an OsFriendly output alongside OsMajor/OsMinor would fix that, but just thinking out loud here.

**Comment by thyn** [comment]
https://github.com/karma-runner/karma/pull/3201

**Comment by thyn** [comment]
was fixed about a year ago
